version: "3" 
services:
  db:
    image: mariadb:latest
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: ${WORDPRESS_DB_NAME}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_USER: ${WORDPRESS_DB_USER}
      MARIADB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
    volumes:
      - ${DATADIR}/mysql:/var/lib/mysql
  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    restart: unless-stopped
    ports:
      - "7642:80"
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
    volumes:
      - ${DATADIR}/wp:/var/www/html
  phpmyadmin:
    image: phpmyadmin:latest
    restart: unless-stopped
    links:
      - db
    environment:
    # PMA_HOSTS: db, db2 # allow for multiple hosts
      PMA_HOST: db
      PMA_ARBITRARY: 1 # allows for changing db in phpmyadmin web interface
    ports:
      - "7643:80"