services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - VERSION=docker
      - PLEX_CLAIM=${CLAIM}
    volumes:
      - ${LOCALCONFIG}/plex:/config
      - ${SYNOLOGY}/media/music:/music
      - ${SYNOLOGY}/media/tv:/tv
      - ${SYNOLOGY}/media/movies:/movies
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ${LOCALCONFIG}/sonarr:/config
      - ${SYNOLOGY}:/data
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ${LOCALCONFIG}/radarr:/config
      - ${SYNOLOGY}:/data
    ports:
      - 7878:7878
    restart: unless-stopped
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - ${LOCALCONFIG}/jackett:/config
    ports:
      - 9117:9117
    restart: unless-stopped
  flaresolverr:
    # DockerHub mirror flaresolverr/flaresolverr:latest
    image: 21hsmw/flaresolverr:nodriver 
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=America/Los_Angeles
      - DRIVER=nodriver
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped