services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - VERSION=docker
      - PLEX_CLAIM=${CLAIM}
    volumes:
      - ${LOCALCONFIG}/plex:/config
      - ${SYNOLOGY}/media/music:/music
      - ${SYNOLOGY}/media/tv:/tv
      - ${SYNOLOGY}/media/movies:/movies
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ${LOCALCONFIG}/sonarr:/config
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ${LOCALCONFIG}/radarr:/config
      - ${SYNOLOGY}:/data
    ports:
      - 7878:7878
    restart: unless-stopped
