services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - VERSION=docker
      - PLEX_CLAIM=${CLAIM}
    volumes:
      - ${SYNOLOGY}/plex-conf:/config
      - ${SYNOLOGY}/music:/music
    restart: unless-stopped
