version: "2.1"
services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/Los_Angeles
      - VERSION=docker
      - PLEX_CLAIM=${CLAIM}
    volumes:
      - ${DATADIR}/plex-conf:/config
      - ${DATADIR}/tv:/tv
      - ${DATADIR}/movies:/movies
      - ${DATADIR}/music:/music
    restart: unless-stopped