---
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - WEBUI_PORT=20480
    volumes:
      - /home/carson/Synology/webapps/qbittorrent/config:/config
      - /home/carson/Synology/webapps/qbittorrent/torrents:/downloads
    ports:
      - 20480:20480
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped