version: "2"
services:
  baikal:
    container_name: baikal
    image: ckulka/baikal:nginx
    restart: unless-stopped
    ports:
      - "3264:80"
    volumes:
      # Remember to change ownership for nginx: chown -R 101:101 config Specific
      - ${LOCALCONFIG}/baikal/config:/var/www/baikal/config
      - ${LOCALCONFIG}/baikal/config:/var/www/baikal/Specific