services:
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - VERSION=docker
      - PLEX_CLAIM=${CLAIM}
    volumes:
      - ${LOCALCONFIG}/plex:/config
      - ${SYNOLOGY}/music:/music
      - ${SYNOLOGY}/tv:/tv
      - ${SYNOLOGY}/movies:/movies
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${LOCALCONFIG}/sonarr:/config
      - ${SYNOLOGY}:/data
    ports:
      - 8989:8989
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${LOCALCONFIG}/radarr:/config
      - ${SYNOLOGY}:/data
    ports:
      - 7878:7878
    restart: unless-stopped
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${LOCALCONFIG}/bazarr:/config
      - ${SYNOLOGY}:/data #optional
    ports:
      - 6767:6767
    restart: unless-stopped
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - AUTO_UPDATE=true #optional
      - RUN_OPTS= #optional
    volumes:
      - ${LOCALCONFIG}/jackett:/config
    ports:
      - 9117:9117
    restart: unless-stopped
  flaresolverr:
    # Using fork of flaresolverr for TL
    image: 21hsmw/flaresolverr:nodriver 
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=${TZ}
      - DRIVER=nodriver
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
  ombi:
    image: linuxserver/ombi
    container_name: ombi
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
    volumes:
      - ${LOCALCONFIG}/ombi:/config
    ports:
      - 3579:3579
    restart: unless-stopped
