services:
  readeck:
    image: codeberg.org/readeck/readeck:latest
    container_name: readeck
    ports:
      - 3695:8000
    environment:
      # Defines the application log level. Can be error, warn, info, debug.
      - READECK_LOG_LEVEL=info
      # The IP address on which Readeck listens.
      - READECK_SERVER_HOST=0.0.0.0
      # The TCP port on which Readeck listens. Update container port above to match (right of colon).
      - READECK_SERVER_PORT=8000
      # The URL prefix of Readeck.
      - READECK_SERVER_PREFIX=/
      # A list of hostnames allowed in HTTP requests. Required for reverse proxy configuration.
      - READECK_ALLOWED_HOSTS=read.carsonferreira.com
    volumes:
      - ${LOCALCONFIG}:/readeck
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "/bin/readeck", "healthcheck", "-config", "config.toml"]
      interval: 30s
      timeout: 2s
      retries: 3
  linkding:
    container_name: "linkding"
    image: sissbruecker/linkding:latest
    environment:
      - LD_SUPERUSER_NAME=${NAME}
      - LD_SUPERUSER_PASSWORD=${PASS}
    ports:
      - "3000:9090"
    volumes:
      - ${LOCALCONFIG}:/etc/linkding/data
    restart: unless-stopped